### ISSUE TITLE
Reason: TypeError: Cannot read property 'node' of undefined

### ISSUE THREAD

**Issue by DimisMeu** [Frostbourn/instagram-widget#1]
i got this error for some public profiles only, 

Uncaught (in promise) Unable to retrieve photos. Reason: TypeError: Cannot read property 'node' of undefined

i do some edits and its work perfectly but with some account not. Although it capture name account profile image number of posts, followers and followings!

**Comment by Frostbourn** [comment]
Hi
Can you give me some steps to reproduce this bug?

**Comment by DimisMeu** [comment]
in your **initial downloaded script**, change user name to mine account: data-user="dimism.eu"
works perfect! (Try for a friend @kiapek, not working..)
I made one for https://www.zaxarakis-tavern.gr/ with minor changes works fine!
Then i tryagain  for @portopefko or @xrisiakti
-> https://www.instagram.com/portopefko/
-> https://www.instagram.com/xrisiakti/
and got the same error! The accounts are public, and professional as mine!

---

PS: Some changes i made after all:
<a href="h t t p s://w w  w.instagram .com/${widgetSetting.id}/" target="_blank" rel="noopener noreferrer"><img src="${userData.profile_pic_url_hd}" class="widget-header__avatar">
<span class="widget-header__username">${userData.full_name} - ${userData.username}</span></a>
<span class="widget-header__logo"><a href="h t t p s://w w w.instagram .com/${widgetSetting.id}/" target="_blank" rel="noopener noreferrer"><img src="../img/ig-logo-email.png" width="40px" /></a></span>
                        
ADD: 
commentCount: node.edge_media_to_comment.count,
timestamp: node.taken_at_timestamp

FOR:
<p>${caption}</br></br>
<span>&#x2764;</span> ${nFormat(likesCount)} <span>&#128172;</span> ${nFormat(commentCount)}</br>${timestamp}
 </p>

Only need to convert timestamp to date!

Thanks for your response!

**Comment by Frostbourn** [comment]
I fixed this issue in the latest commit.

To conver the timestamp to date check out this [question](https://stackoverflow.com/questions/847185/convert-a-unix-timestamp-to-time-in-javascript).

**Comment by DimisMeu** [comment]
Thank you!
